image: registry.secoder.net/tool/deployer

stages:
  - build
  - test
  - deploy

build-master:
  stage: build
  script: 
    - cp ./.env.master ./.env
    - export BUILD_IMAGE_NAME=$CI_REGISTRY_IMAGE
    - export BUILD_IMAGE_TAG=$CI_COMMIT_REF_SLUG
    - export BUILD_IMAGE_USERNAME=$CI_REGISTRY_USER
    - export BUILD_IMAGE_PASSWORD=$CI_REGISTRY_PASSWORD
    - deployer build
  only: 
    - master

build-feature:
  stage: build
  script: 
    - cp ./.env.feature ./.env
    - export BUILD_IMAGE_NAME=$CI_REGISTRY_IMAGE
    - export BUILD_IMAGE_TAG=$CI_COMMIT_REF_SLUG
    - export BUILD_IMAGE_USERNAME=$CI_REGISTRY_USER
    - export BUILD_IMAGE_PASSWORD=$CI_REGISTRY_PASSWORD
    - deployer build
  except:
    - master

.test:
  image: node:18
  stage: test

  before_script:
    - yarn config set registry https://registry.npmmirror.com
    - yarn install

style-test:
  extends: .test
  allow_failure: true

  script:
    - yarn lint
    - ret=$?
    - exit $ret

unit-test:
  extends: .test
  allow_failure: true
  script:
    - yarn test
    - ret=$?
  after_script:
    - SUFFIX=$RANDOM
    - curl "http://api.secoder.net/static/sonar-scanner.tar.gz" -s -o "/tmp/sonar-$SUFFIX.tar.gz"
    - tar -xf "/tmp/sonar-$SUFFIX.tar.gz" -C /opt
    - /opt/sonar-scanner/bin/sonar-scanner

deploy-master:
  stage: deploy
  script:
    - deployer dyno replace $CI_PROJECT_NAME "$CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG" "$REGISTRY_USER" "$REGISTRY_PWD"
  only: 
    - master 
    
deploy-feature:
  stage: deploy
  script:
    - deployer dyno replace frontend-feature "$CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG" "$REGISTRY_USER" "$REGISTRY_PWD"
  except: 
    - master 
    
